---
root:
  - env: PULUMI_CONFIG_PASSPHRASE
    type: secret_string
    default: ""
    optional: true
    help: >
      Enter the passphrase used to encrypt and decrypt the private key. This value is required if you're not using Pulumi
      Cloud.
  - env: DATAROBOT_DEFAULT_USE_CASE
    type: string
    default:
    optional: true
    help: "Enter the default use case for this application. If not set, a new use case will be created automatically."
  - env: DATAROBOT_DEFAULT_PREDICTION_ENVIRONMENT
    type: string
    default:
    optional: true
    help: "Enter the default prediction environment for this application. If not set, a new prediction environment will be
      created automatically."
